### ISSUE TITLE
Nav Items as in the examples are not clickable if not clicked exactly on the text

### ISSUE THREAD

**Issue by OrKoN** [vcl/navigation#2]
I would expect that the entire highlighted item is clickable, not only the text.

If clicked here:

![image](https://cloud.githubusercontent.com/assets/399150/6886081/9e904a2e-d632-11e4-96c9-6293a6352a9b.png)

nothing happens

**Comment by vanthome** [comment]
Historically with XHTML which the VCL used previosuly is was not possible to wrap anchors but with HTML 5 its legalized. [Fixed it](https://github.com/vcl/navigation/commit/81f255a991433aa9aedfcedf58850fcead4a3449). It's just a change of tags. Cany you do that in the eVCL component? However this is not really relevant when used with components as the event handler was already on the whole icogram so this is only relevant if you build a static site.
